---
# Read about `build.yaml` at https://pub.dev/packages/build_config
# TODO: this should/can be overridden depending on your domain??
targets:
  $default:
    builders:
  scorekeeper_domain:
    builders:
      handler_generator:
        generate_for:
          - lib/src/contest.dart
      aggregate_dto_generator:
        generate_for:
          - lib/src/contest.dart
      aggregate_dto_factory_generator:
        generate_for:
          - lib/src/contest.dart
      domain_serializer_generator:
        generate_for:
          - lib/src/contest.dart

builders:
  handler_generator:
    import: "package:scorekeeper_codegen/generator.dart"
    builder_factories: ["handlerGenerator"]
    build_extensions: {".dart": [".h.dart"]}
    auto_apply: dependents
    build_to: source
  aggregate_dto_generator:
    import: "package:scorekeeper_codegen/generator.dart"
    builder_factories: [ "aggregateDtoGenerator" ]
    build_extensions: { ".dart": [ ".d.dart" ] }
    auto_apply: dependents
    build_to: source
  aggregate_dto_factory_generator:
    import: "package:scorekeeper_codegen/generator.dart"
    builder_factories: ["aggregateDtoFactoryGenerator"]
    build_extensions: {".dart": [".f.dart"]}
    auto_apply: dependents
    build_to: source
  domain_serializer_generator:
    import: "package:scorekeeper_codegen/generator.dart"
    builder_factories: ["serializerGenerator"]
    build_extensions: {".dart": [".s.dart"]}
    auto_apply: dependents
    build_to: source
