---
name: scorekeeper_example_domain
description: An example domain that can be used with the scorekepeer application
version: 0.0.1-dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  scorekeeper_domain:
    path: ../scorekeeper_domain
  uuid: ^3.0.3


dev_dependencies:
  build_config: ^0.4.5
  build_runner: ^1.10.12
  build_verify: ^1.1.1
  build_version: ^2.0.1
  pedantic: ^1.9.0
  scorekeeper_codegen:
    path: ../scorekeeper_codegen
  test: ^1.14.4
  # test_coverage: ^0.5.0
