name: scorekeeper_core
description: The core library for the scorekeeper application
version: 0.0.1-dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  uuid: ^2.2.2
  scorekeeper_domain:
    path: ../scorekeeper_domain
  example_domain:
    path: ../scorekeeper_example_domain

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
