---
name: scorekeeper_domain_contest
description: The Contest domain that can be used with the scorekepeer application
version: 0.0.1-dev
homepage: https://scorekeeper.io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: 2.0.0
  scorekeeper_domain:
    path: ../scorekeeper_domain
  uuid: ^3.0.3


dev_dependencies:
  build_config: ^0.4.5
  build_runner: ^1.10.12
  build_verify: ^2.0.0
  build_version: ^2.0.1
  pedantic: ^1.9.0
  scorekeeper_codegen:
    path: ../scorekeeper_codegen
  scorekeeper_core:
    path: ../scorekeeper_core
  test: ^1.14.4
  # test_coverage: ^0.5.0
