name: scorekeeper_event_store_moor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1-dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#
#  json_annotation: ^4.0.1
#  json_serializable: ^4.1.3


  # Core package defining most API's
  moor: ^4.3.0
  # used to find suitable location to store sqlite database
  path: ^1.8.0
  path_provider: ^2.0.1
  scorekeeper_core:
    path: ../scorekeeper_core
  # ships with latest sqlite3 version for Android or IOS
  sqlite3_flutter_libs: ^0.4.3

dev_dependencies:
  # Common tool for code-generation
  build_runner: ^1.10.12
  flutter_test:
    sdk: flutter
  # Used to generate query code based on tables
  moor_generator:
  # We cannot prevent build_runner/build_config to pick up the build.yaml file from scorekeeper_domain.
  # This package doesn't define any matching "contest.dart" files, so nothing will be generated by those builders.
  # Still, since they're configured that way, we'll have no choice but to make sure the scorekeeper_codegen lib is a known dev dependency.
  scorekeeper_codegen:
    path: ../scorekeeper_codegen
  test: ^1.14.4
  protobuf: 2.0.0
  uuid: ^3.0.3

  # for the test domain stuff...
  scorekeeper_domain:
    path: ../scorekeeper_domain


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
