name: scorekeeper_codegen
description: Library used for code generation for custom domain libraries
version: 0.0.1-dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  scorekeeper_domain:
    path: ..\scorekeeper_domain
  # dependencies required for generating code using the build package
  build: ^1.6.1
  source_gen: ^0.9.10+1
  analyzer: ^0.41.1
  code_builder: 3.5.0
  dart_style: 1.3.10


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
